### ISSUE TITLE
[BitSet] entries()/values() don't work when length=32

### ISSUE THREAD

**Issue by PhilippeMorier** [Yomguithereal/mnemonist#117]
If we have a `Bitset` of 32 bits, it is not possible to iterate over the `entries`/`values`.

The following test is failing when we create `new Bitset(32)` but works with `new Bitset(31)` or `new Bitset(33)`.

```JavaScript
it('should iterate over entries', function() {
    var set = new BitSet(32);

    var iterator = set.entries();
    var result = iterator.next();
    var counter = 0;

    while (!result.done) {
      assert.deepEqual(result.value, [counter, 0]);
      result = iterator.next();
      counter++;
    }

    assert.strictEqual(counter, set.length);
  });
```

Possible place of error:

```JavaScript
// If we have a set with a length which is a multiple of 32,
// we maybe need to check `i === l` and not `i === l - 1`?
b = i === l - 1 ? length % 32 : 32;
```

Maybe I am missing something :innocent:. @Yomguithereal WDYT?

**Comment by Yomguithereal** [comment]
This line is indeed the culprit and does not take the length of the bitset being a multiple of 32 (the case with 64, 128 etc. should also fail). Do you want to draft a fix?

**Comment by Yomguithereal** [comment]
Also I think the `#.select` method must suffer from the same issue.

**Comment by Yomguithereal** [comment]
And `#.forEach` also.

**Comment by Yomguithereal** [comment]
And we could cache some part of the end index outside of the loop. I might be able to fix this tomorrow though if you don't want to.

**Comment by PhilippeMorier** [comment]
Hey @Yomguithereal, I am still not completely sure what is going on. So if you know how to quickly fix it that would be awesome.

**Comment by Yomguithereal** [comment]
Hello @PhilippeMorier,

I think your understanding of the variables is correct except for `b` which is the byte allocated length (which is 32 except for the last one that can be different) instead of the max index.

I have pushed a fix. In the meantime I have spotted another issue regarding the `#.select` method which I will correct before releasing a v0.31.2.

**Comment by PhilippeMorier** [comment]
Hey @Yomguithereal,

cool, thanks for your explanation and fix :muscle:. I like `b = length % 32 || 32;`.

Ok, good to know.

**Comment by Yomguithereal** [comment]
v0.31.2 is live on npm
