### ISSUE TITLE
Heap.{nsmallest, nlargest} mixed up parameter order

### ISSUE THREAD

**Issue by klmntoth** [Yomguithereal/mnemonist#119]
In the heap.js file the [nsmallest](https://github.com/Yomguithereal/mnemonist/blob/master/heap.js#L197) and [nlargest](https://github.com/Yomguithereal/mnemonist/blob/master/heap.js#L292) functions have `(compare, n, iterable)` parameter list, but in the [typings](https://github.com/Yomguithereal/mnemonist/blob/master/heap.d.ts#L81) file and the [docs](https://yomguithereal.github.io/mnemonist/heap#nsmallest) its `(n: number, comparator: HeapComparator<T>, values: Iterable<T>)`

**Comment by Yomguithereal** [comment]
Hello @klmntoth. This is a problem indeed. Let me fix that soon.
