### ISSUE TITLE
Heap.{nsmallest, nlargest} doesn't uses the comparator when n = 1

### ISSUE THREAD

**Issue by klmntoth** [Yomguithereal/mnemonist#120]
[heap.js](https://github.com/Yomguithereal/mnemonist/blob/master/heap.js#L308): when n = 1, the two function doesn't uses the comparator, so its not working with object arrays this case

**Comment by Yomguithereal** [comment]
Indeed, I will fix that for the next release.

**Comment by Yomguithereal** [comment]
V0.31.3 should be released now with a fix.
