### ISSUE TITLE
new Structure(structure) pattern

### ISSUE THREAD

**Issue by xamgore** [Yomguithereal/mnemonist#142]
Constructing a data structure from another data structure is a common pattern in Java and even Javascript:

```js
new Set(new Set([1, 2, 3]))  // {1, 2, 3}
```

Would you like to get a PR implementing it?

**Comment by Yomguithereal** [comment]
Hello @xamgore. JavaScript is a bit inconsistent on this particular point. `new Array` does not have the same semantics as `new Set` in this regard for instance. So I chose to implement this use case as the many static `#.from` methods you can find across the library. For instance you can:

```js
MultiSet.from(new Set([1, 2, 3]));
```

I feel it covers the usecase quite nicely and does not overcomplicate the constructor implementations. What do you think?

**Comment by xamgore** [comment]
A good example is `Buffer` class, it also has `Buffer.from` method and `new Buffer` has been deprecated since Node v10. I don't know the reasons, though.
 
Thank you for the fast response 😌, I will send a PR with `DefaultMap.from` then.

**Comment by Yomguithereal** [comment]
I don't remember why I skipped adding a `#.from` to the DefaultMap... Maybe there is some kind of conceptual problem with it you will stumble upon while implementing. Or maybe I was just lazy or forgot :) Who knows? I'll wait for your PR then.
