### ISSUE TITLE
Move duplicate code in LRUCache and LRUMap to one place

### ISSUE THREAD

**Issue by trivikr** [Yomguithereal/mnemonist#159]
### Is your request related to a problem? Please describe.
There is lot of duplicate code between `lru-cache.js` and `lru-map.js`.

For example, let us compare the set operations:
* LRUCache https://github.com/Yomguithereal/mnemonist/blob/825538adaf1daee4b9ce3f6c073956ed4211ea1e/lru-cache.js#L107-L140
* LRUMap https://github.com/Yomguithereal/mnemonist/blob/825538adaf1daee4b9ce3f6c073956ed4211ea1e/lru-map.js#L67-L100

The only difference if `set`, `get` and `delete` operations on `this.items`.

This duplicate code can lead to bugs by contributors, if code is not copied correctly.
For example, while implementing remove functionality in LRUCache and LRUMap, the bugfix to decrement `this.removedSize` in prefix wasn't done in LRUMap. It was added in a separate commit [`8bb720a` (#154)](https://github.com/Yomguithereal/mnemonist/pull/154/commits/8bb720a19a7c432b2f9a678cb517a389afd5f39f) while reading the diff for the PR.

The only difference between LRUCache and LRPMap is `this.items` property, which is:
* an object in case of LRUCache.
* a map in case of LRUMap.

### Describe the solution you'd like
Create a function LRU which includes common functionalities. It makes following assumptions about `this.items` property:
* it is set by the derived class
* it imitates map APIs `set`, `get`, `delete`, `has` and `clear`.

The LRUCache and LRUMap function will call LRU, and set their prototype to that of LRU.

<details>
<summary>lru.js</summary>

```js
/**
 * Mnemonist LRU
 * =================
 *
 * Base implementation for LRUCache and LRUMap.
 * The items property needs to be set by derived class, and it should imitate Map APIs.
 */

function LRU(Keys, Values, capacity) {
  if (this.constructor === LRU) {
    throw new Error("Can't instantiate abstract class LRU!");
  }
  ...
 // this.items = {}; <-- An equivalent implementation would be set in LRUCache
 // this.items = new Map(); <-- This would be set in LRUMap
}

LRU.prototype.clear = function() {
  ...
  this.items.clear(); // <-- Assumes this.items follows map API clear
}

LRU.prototype.set = function(key, value) {
  var pointer = this.items.get(key); // <-- Assumes this.items follows map API get
  ...
  // Deletion when cache is full
  this.items.delete(this.K[pointer]); // <-- Assumes this.items follows map API delete
  ...
  this.items.set(key, pointer); // <-- Assumes this.items follows map API set
}

LRU.prototype.has = function(key) {
  return this.items.has(key); // <-- Assumes this.items follows map API has
};

module.exports = LRU;
```

</details>

<details>
<summary>lru-map.js</summary>

```js
/**
 * Mnemonist LRUMap
 * =================
 *
 * Variant of the LRUCache class that leverages an ES6 Map instead of an object.
 * It might be faster for some use case but it is still hard to understand
 * when a Map can outperform an object in v8.
 */

var LRU = require('./lru.js');

function LRUMap(Keys, Values, capacity) {
  LRU.call(this, Keys, Values, capacity);
  this.items = new Map();
}
LRUMap.prototype = Object.create(LRU.prototype);

module.exports = LRUMap;
```

</details>

<details>
<summary>lru-cache.js</summary>

```js
/**
 * Mnemonist LRUCache
 * ===================
 *
 * JavaScript implementation of the LRU Cache data structure. To save up
 * memory and allocations this implementation represents its underlying
 * doubly-linked list as static arrays and pointers. Thus, memory is allocated
 * only once at instantiation and JS objects are never created to serve as
 * pointers. This also means this implementation does not trigger too many
 * garbage collections.
 *
 * Note that to save up memory, a LRU Cache can be implemented using a singly
 * linked list by storing predecessors' pointers as hashmap values.
 * However, this means more hashmap lookups and would probably slow the whole
 * thing down. What's more, pointers are not the things taking most space in
 * memory.
 */

var LRU = require('./lru.js');

function LRUCache(Keys, Values, capacity) {
  LRU.call(this, Keys, Values, capacity);
  this.items = {
    items: {},
    set: function(key, value) {
      this.items[key] = value;
    },
    get: function(key) {
      return this.items[key];
    },
    has: function(key) {
      return key in this.items;
    },
    delete: function(key) {
      delete this.items[key];
    },
    clear: function() {
      this.items = {};
    }
  };
}
LRUCache.prototype = Object.create(LRU.prototype);

module.exports = LRUCache;
```

</details>

StackOverflow discussion: https://stackoverflow.com/a/21220964

### Describe alternatives you've considered
Using ES6 classes for inheritance. This is not recommended, as we want mnemonist algorithms to work on legacy browsers and resource-constrained environments like IoT devices.

### Additional context
If approved by maintainer, I would like to implement this request.
I would like the remove functionality in https://github.com/Yomguithereal/mnemonist/pull/154 to be merged in master first, so that this refactor can be done on top of it.

**Comment by Yomguithereal** [comment]
Hello @trivikr, as stated in PR #154, this redundant code does exists for my own pleasure :). I would love it to go away but the fact is your wrapper on top of the object will multiply the number of function calls made by the `LRUCache` class and this will slow it down significantly.

**Comment by trivikr** [comment]
> I would love it to go away but the fact is your wrapper on top of the object will multiply the number of function calls made by the `LRUCache` class and this will slow it down significantly.

This issue can be closed as the duplicate code exists for performance reasons.
