### ISSUE TITLE
KDTree constructor not working as documented

### ISSUE THREAD

**Issue by olastor** [Yomguithereal/mnemonist#192]
Using [the example from the docs](https://yomguithereal.github.io/mnemonist/kd-tree):
```
var data = [
  ['zero', [2, 3]],
  ['one', [5, 4]],
  ['two', [9, 6]],
  ['three', [4, 7]],
  ['four', [8, 1]],
  ['five', [7, 2]]
];

var tree = new KDTree(data, 2);

tree.dimensions
```

the typescript compiler fails, saying

```
TS2554: Expected 0 arguments, but got 2.
    88 |         ];
    89 |
  > 90 |         var tree = new KDTree(data, 2);
```

**Comment by olastor** [comment]
I think the docs should be changed to `KDTree.from` in the examples.

**Comment by Yomguithereal** [comment]
Hello @olastor. You are right the examples are wrong. Do you want to fix them by opening a PR on the `gh-pages` branch of this repo holding the docs?

**Comment by olastor** [comment]
@Yomguithereal I've opened https://github.com/Yomguithereal/mnemonist/pull/194

**Comment by Yomguithereal** [comment]
Thanks @olastor. I have merged your PR. The online docs should be updated shortly.
