### ISSUE TITLE
Structures to add

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/mnemonist#2]
- [x] Bags (Multiset, Counter)
- [ ] BloomFilter
- [ ] Deque
- [ ] Doubly Linked List
- [x] Fibonacci Heap
- [x] Linked List
- [x] Heap
- [x] Queue
- [ ] Radix Tree
- [x] Stack
- [ ] Suffix Tree (Ukkonen)
- [x] Suffix Array
- [x] Trie
- [ ] Inverted Index (simple & complex)
- [ ] Index & MultiIndex

**Comment by Yomguithereal** [comment]
@jacomyma, @jacomyal any request?

**Comment by jacomyma** [comment]
Ah, he already has tries and bloom filters :) !
Helpers for bit arrays maybe? Binary tree? I don't know, you seem to cover the essentials.

**Comment by Yomguithereal** [comment]
Just added the Trie.

**Comment by Yomguithereal** [comment]
Just finished the Fibonacci Heap. Djikstra & A*, here I come!

**Comment by Yomguithereal** [comment]
I could add UnionFind but I doubt it has a sense in a high-level language.
