### ISSUE TITLE
Change import path as true name for clarity

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/mnemonist#20]
For the time being, one requires a structure likewise:

```js
var LinkedList = require('mnemonist/linked-list');
```

Would it be better to have:

```js
var LinkedList = require('mnemonist/LinkedList');
```

@jacomyal what do you think of this?

**Comment by jacomyal** [comment]
I totally arbitrarily prefer `var LinkedList = require('mnemonist/linked-list');` and I can't say why.

**Comment by Yomguithereal** [comment]
Case closed then.
