### ISSUE TITLE
What is the simple way of copying all elements from one Multiset into another?

### ISSUE THREAD

**Issue by kberg** [Yomguithereal/mnemonist#201]
This is the most efficient way I can think of to copy between multisets. Is there something in the API that's simpler?

```
source.forEachMultiplicity((count, key) => destination.add(key, count));
```

(Also, why are count and key in a different order in forEachMultiplicity, anyway?

**Comment by Yomguithereal** [comment]
> This is the most efficient way I can think of to copy between multisets. Is there something in the API that's simpler?

Your example is probably the best solution currently. I can add a `#.copy` method that could do so faster if you feel this would be useful.

> (Also, why are count and key in a different order in forEachMultiplicity, anyway?

Once again to adhere to ES6's strange (but explainable) standards on the matter (they wanted to be consistent with array.forEach argument ordering). An ES6 map forEach callback gives the value before the key. I could use my own standard on the matter but it would make iterate over mixed collections more of a pain in this context.

**Comment by kberg** [comment]
OK. Well, I hear you. Let's close these, then. Thanks.
