### ISSUE TITLE
Add Composite Index to the documentation

### ISSUE THREAD

**Issue by svnv** [Yomguithereal/mnemonist#23]
I found the [Composite Index](https://yomguithereal.github.io/mnemonist/composite-index) when reading about Index, but it is not in [the list on the github page](https://yomguithereal.github.io/mnemonist) or in the readme.

**Comment by Yomguithereal** [comment]
Hello @svnv. This is actually quite simple: the documentation for the `CompositeIndex` is already written but the code is not. I should probably hide it and remove the link for now until the code is written.

**Comment by Yomguithereal** [comment]
Done. It should be hidden now :)
