### ISSUE TITLE
suggestion to standardize Iterate callback's arguments

### ISSUE THREAD

**Issue by Rayraegah** [Yomguithereal/mnemonist#29]
Wouldn't it be better to standardize the callback in iterate with `(value, index|key, target)`?

in [iterate.js](https://github.com/Yomguithereal/mnemonist/blob/master/utils/iterate.js):

line 21 

    callback(target[i], i)

vs line 27 ([Array.prorotype.forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach))

    target.forEach(callback)

Also, if callback returns false break the loop.

**Comment by Yomguithereal** [comment]
Hello @Rayraegah. The difference between both lines you show is the target scope, no? But since this function is only used internally and is not exposed, why do we need the target scope?

I cannot break the loop if callback returns `false`. What if `false` is actually a value you are iterating upon?

**Comment by Rayraegah** [comment]
I cloned the project and tested my suggestions out (should have done that first). You're right.

**Comment by Yomguithereal** [comment]
Did you have issues with the behavior of a static `#.from` function? Is that how you came to the harmonized iteration function?

**Comment by Rayraegah** [comment]
> Did you have issues with the behavior of a static #.from function? Is that how you came to the harmonized iteration function?

Yes. I was trying to use in a weird way and found iteration modifying original object via a pointer reference. To be honest, internally it doesn't affect anything.

```

  // The collection is an iterator
  if (typeof collection.next === 'function') {
    iterator = collection; // modifies collection object
    i = 0;

    while ((s = iterator.next(), !s.done)) {
      iteratee(s.value, i, collection);
      i++;
    }

    return;
  }
```

The last test case would yield

```
Original: MapIterator { 1, 2, 3 } <===> Reference: MapIterator { 2, 3 }
Original: MapIterator { 1, 2, 3 } <===> Reference: MapIterator { 3 }
Original: MapIterator { 1, 2, 3 } <===> Reference: MapIterator {  }
```

**Comment by Yomguithereal** [comment]
Since we need to consume the iterator, I guess this is to be expected, no?

**Comment by Rayraegah** [comment]
> Since we need to consume the iterator, I guess this is to be expected, no?

When you add a new data-structure that would need this feature, then you can modify iterator :) otherwise its okay.
