### ISSUE TITLE
Support for types

### ISSUE THREAD

**Issue by zzx88991** [Yomguithereal/mnemonist#34]
This is a cool library. Data structure has growing importance on FE since more logic is pushed to client side. It would be nice if this library can have [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) 😄

**Comment by Yomguithereal** [comment]
I would love to have typings for the library (probably more through this repo & the typings field of the package.json than through definitelytyped though, I hear this is now the rad thing to do?). Unfortunately, I don't feel skilled enough in TypeScript to do so properly.

I would gladly consider a PR with this addition however. This could start by only typing a single structure and then following with the rest later when we feel confident with the chosen model.

**Comment by kralcifer** [comment]
I put up a PR for the start of a TypeScript type declarations file.  Works for the classes I'm using.  It's on the trie-map branch.

**Comment by Yomguithereal** [comment]
Well there are types now :)

**Comment by fuhrmanator** [comment]
I'm struggling with types of a MultiSet in VSCode. `new MultiSet()` has type `any`? Is that correct? It also seems that you can't have a generic e.g., `MultiSet<string>`.

![image](https://user-images.githubusercontent.com/7606540/180902750-834660ba-f4c0-4d97-9991-382ba9698cec.png)

```typescript
var MultiSet = require('mnemonist/multi-set');

// ...

const projetsMultiset = new MultiSet();
```

**Comment by Yomguithereal** [comment]
Hello @fuhrmanator,

> new MultiSet() has type any? Is that correct?

No it's not.

>  It also seems that you can't have a generic e.g., MultiSet<string>.

You very well can, as stated by this declaration file: https://github.com/Yomguithereal/mnemonist/blob/master/multi-set.d.ts

I think there is something wrong here. Either you installed a very old version of the library, or your TS or VSCode integration is not set up properly. Sometimes, just closing and re-opening VSCode does the trick.

**Comment by fuhrmanator** [comment]
> It also seems that you can't have a generic e.g., MultiSet.

>> You very well can, as stated by this declaration file: https://github.com/Yomguithereal/mnemonist/blob/master/multi-set.d.ts

The problem finally was the import. I removed it and let VSCode propose a quick fix:

```typescript
import { MultiSet } from 'mnemonist';
```

I had mistakenly used the import from the [documentation](https://yomguithereal.github.io/mnemonist/multi-map) which says (generically?) to use

```javascript
var MultiMap = require('mnemonist/multi-map');
```

Thanks for your help!

**Comment by fuhrmanator** [comment]
Yes. That was the second quick-fix VSCode proposed.
![image](https://user-images.githubusercontent.com/7606540/181052145-fc736b94-5f0c-417d-a302-92e095d5ba0e.png)
