### ISSUE TITLE
running symspell test cannot find module damerau-levenshtein

### ISSUE THREAD

**Issue by xthdraft** [Yomguithereal/mnemonist#46]
Your test utility for symspell specifies:  damerauLevenshtein = require('damerau-levenshtein');

Running the test suite using  "mocha symspell.js" from the folder containing test\symspell.js produces this error:
Cannot find module 'damerau-levenshtein'

I tried to use the version on npm by installing globally:  npm install --global damerau-levenshtein

This did not prevent the error message described above.

Would you please advise where the required damerau-levenshtein file is to be found.  Shouldn't it be part of the mnemonist package?

Many thanks.

**Comment by Yomguithereal** [comment]
Hello @xthdraft. The `damerau-levenshtein` package is correctly listed in this package's `devDependencies` here: https://github.com/Yomguithereal/mnemonist/blob/master/package.json#L51.

To run the library's unit tests, just install the packages dependencies and run `npm test`:

```
npm install
npm test
```

**Comment by xthdraft** [comment]
Thank you. Yes, I have it working now.
