### ISSUE TITLE
identifier data to associate with Trie items

### ISSUE THREAD

**Issue by kralcifer-ms** [Yomguithereal/mnemonist#74]
@Yomguithereal am I missing something?  I have a bunch of entities that I want to use a Trie for fast lookup by their name field which can be 1 to 5 words long.  I can add names of course and 'get' matching results but I don't have a way to associate the matches with their entitities.  I'm used to APIs like this allowing a tag or index or identifier so I can hook it up to a match upon receiving the matching results.

**Comment by Yomguithereal** [comment]
Hello @kralcifer-ms. I guess that what you need is a `TrieMap` so you can associate values to your keys and not just have a `Set` like structure. Do I understand correctly? If you want I can implement this very soon. Just know that in some cases, with the current implementation relying heavily on JS objects, a single Map can sometimes work better. But I am also currently on very low-level implementations that will trump the Map very well.

**Comment by kralcifer-ms** [comment]
I briefly read about TrieMap but I'm not sure that will help me either.  Best I can do is describe my scenario a bit more in hopes you might have another suggestion.   I'll use the volleyball app I'm currently working on.  They are organized in the form of clubs and each club can have several teams and can host events.  The names of all the types of entities is pretty loose causing users problems when they go to try to lookup something by name.  One example would be a club named 'Sudden Impact VBC' with team names like 'SIVBC 16 Thunder' and 'SIVBC Typhoon 15-1'.  A user may try to find them by searching for 'sudden impact' or 'sivbc' or 'thunder'.  Another good example is an event name like '2018 NW Jrs Presidents Weekend Tournament' put on by club 'Northwest Juniors VBC' whose own teams have names like 'NW Jrs. 16 UA Blue' or 'NW Jrs. Baden Black'.   One complication is having the year in front `2018 NW...' .  No one will type a year first.  Clubs, teams, and events have unique IDs.  On a project a couple of years ago I wrote my own trie and I believe I submitted the id along with an array of strings and if the trie got a match on any of those strings it would give the id back.  I broke my strings in a unique way because I want the user to be able to cross word boundaries.  So for the team 'NW Jrs. 16 UA Blue' I would add to the trie by giving the team ID along with the array ['NW Jrs. 16 UA Blue', 'Jrs. 16 UA Blue', '16 UA Blue', 'UA Blue', 'Blue'].  If any of the strings in that array were matched by a query to the trie, it would return the team ID so I could easily look up the entities whose name had a search match.

**Comment by Yomguithereal** [comment]
So you definitely need a TrieMap there but you may have to insert several elements per team. On a side note, what you try to perform here is fuzzy matching. There might be better ways to achieve what you want. Things you can try are the SymSpell or the Vantage Point Tree data structure. You should also check [fingerprinting](http://yomguithereal.github.io/talisman/keyers#fingerprint) methods and OpenRefine/Takoyaki's clustering algorithms to inspire yourself.

Currently I am also designing a clustering algorithm based on a Trie and I think it could be turned into a search scheme that would fit your use case. Are your app/data private or could I look it up and see if I can make something work when I find some time?

**Comment by kralcifer-ms** [comment]
I don't have any real data yet, just what I observe in the real world for the app I'm working on.  I have a small amount that I've entered if that's useful.  I'd rather private give it to you but not sure how to do that via github.  I'll look into the things you mentioned.  Thanks for the replies.

**Comment by kralcifer-ms** [comment]
FuzzyMultiMap looks promising.  I'm using TypeScript though and don't know how do make the definition file edits to match the constructor taking in a hash function.

**Comment by kralcifer-ms** [comment]
I'm taking a stab at the typescript declaration file.

I think you have a code comment typo in fuzzy-multi-map.js, line 105:
* @return {any}
 
.has() return type is boolean.

**Comment by Yomguithereal** [comment]
It seems you're right. Do you want to open a PR to fix it? I think the same can be said of fuzzy-map.js since I mostly copied code from the one to the other.

**Comment by kralcifer-ms** [comment]
I tried FuzzyMultiMap but it seems too simple.  It can't really detect much other than wrong casing?  Doesn't look like it would handle misspellings.  SymSpell seems more like a real answer for a fuzzy search.  I'm not convinced that I want a fuzzy search.  I'd like to stick with my plan of prefix matching.  Any chance you could write the TrieMap and let me try it out?  If I understood you correctly when you mentioed "a single Map can sometimes work better", I can send whatever strings that I want prefix searched to the Trie and then maintain my own Map externally for looking up my entities based on the Trie query results.  So what I'm asking for, and hopefully what TrieMap gives, is hiding that Map management so that I don't have to do it externally.  Is that correct?

**Comment by kralcifer-ms** [comment]
Here's what my TypeScript definitions look like so far.  They may not be exact but they were working with the methods I used.

declare module 'mnemonist' {
    export declare class Trie {
        clear(): void;
        add(item: string | string[]): Trie;
        delete(item: string | string[]): boolean;
        has(item: string | string[]): boolean;
        get(prefix: string | string[]): (string | string[])[];
        longestPrefix(item: string | string[]): string | string[];
        inspect(): any;
        toJSON(): any;
    }

    namespace Trie {
        export function from(iterable: Iterator<any>)
    }

    type HashFunc = ((item: any) => any)
    type HashFuncTuple = [HashFunc, HashFunc];
    export declare class FuzzyMultiMap {
        constructor(hashFuncs: HashFunct | HashFuncTuple, container?: any)
        clear(): void;
        add(item: any): FuzzyMultiMap;
        set(key: any, item: any): FuzzyMultiMap;
        get(key: any): any;        
        has(item: any): boolean;
        forEach(callback: (item: any) => any, scope: any): void;
        values(): Iterator;
        inspect(): any;
        [key: any]: any;
    }

    namespace FuzzyMultiMap {
        export function from(iterable: Iterator<any>)
    }
}

**Comment by kralcifer-ms** [comment]
Your example documentation for the constructor taking in a hash function or a tuple of hash functions didn't match the implementation but I could be not understanding how JavaScript (or TypeScript?) handles things.  Specifically:

```
// Let's create an index using two different hash functions:
var map = new FuzzyMultiMap(
  
  // Hash function for inserted items:
  function(movie) {
    return movie.title.toLowerCase();
  },

  // Hash function for queries
  function(query) {
    return query.toLowerCase();
  }
);
``` 
didn't seem to match the impl

```
/**
 * FuzzyMultiMap.
 *
 * @constructor
 * @param {array|function} descriptor - Hash functions descriptor.
 * @param {function}       Container  - Container to use.
 */
function FuzzyMultiMap(descriptor, Container) {
  this.items = new MultiMap(Container);
  this.clear();

  if (Array.isArray(descriptor)) {
    this.writeHashFunction = descriptor[0];
    this.readHashFunction = descriptor[1];
  }
  else {
    this.writeHashFunction = descriptor;
    this.readHashFunction = descriptor;
  }
```
When I passed in 2 functions (like your example) it took the second as Container:

```
new FuzzyMultiMap(insertHash, queryHash)
```

So I had to pass it as tuple:
```
new FuzzyMultiMap([insertHash, queryHash])
```
Also the docs don't mention that you can pass a Container as a second param but probably should.

**Comment by kralcifer** [comment]
Was on with work account earlier but meant to use personal.

Here's what I used for guidance on the TypeScript type declarations:
[TypeScript Handbook - Declaration Files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)

**Comment by Yomguithereal** [comment]
I have updated the JSdocs of the fuzzy map files and fixed documentation according to your suggestions. Re-reading your use case, and since you insert fragment of your strings without specific order, I was wondering if an `InvertedIndex` would be what you actually need. You basically need a basic full text search here, no? It seems you want to return an ID if one or more of the given token in a search are matched in the team name, no?

**Comment by Yomguithereal** [comment]
On a side note, I am starting to rework the Trie a bit to enhance performance etc. and adding the TrieMap.

**Comment by Yomguithereal** [comment]
Hello @kralcifer-ms. I won't have time to make a npm release today but just know there is a working TrieMap object in the `trie-map` branch of this repository if you want to try it before I can release anything.

**Comment by kralcifer** [comment]
Sadness.  I've been working for 4 hours to use TrieMap but no success yet which I'll explain.

@Yomguithereal hoping you can release it so I can consume it.  I see you just updated some documentation on it.

I pulled the branch and am planning on PRing my TypeScript file but trouble on every front just on my side.  React Native doesn't do well with working on an unpublished module.  The packager can't handle sym links.  I tried a few of the workarounds and nothing is working for me.  Then I went to push my TypeScript file for PR and no luck getting the push to work against your repo.  I'm sure it's probably something I'm not set up for correctly on github but if you think it's because your repo is locked down in a way that prevents me, let me know.

**Comment by Yomguithereal** [comment]
I pushed a beta version for you. Run `npm install mnemonist@0.20.0-beta1`. Be sure to read the [code](https://github.com/Yomguithereal/mnemonist/blob/trie-map/trie-map.js) rather than the docs which are not updated to document `TrieMap`. A lot has changed. The API is now more consistent.

I will release a stable version in the week when I find time to reflect changes on the `Trie` and so on...

**Comment by kralcifer** [comment]
Nice!  THanks!

Any ideas on why I can't make a PR?

Here's what my console say:

```
kral_@MSI MINGW64 /d/source/mnemonist2 (trie-map)
$ git status
On branch trie-map
Your branch is ahead of 'origin/trie-map' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

kral_@MSI MINGW64 /d/source/mnemonist2 (trie-map)
$ git checkout -b kralcifer/typescript
Switched to a new branch 'kralcifer/typescript'

kral_@MSI MINGW64 /d/source/mnemonist2 (kralcifer/typescript)
$ git status
On branch kralcifer/typescript
nothing to commit, working tree clean

kral_@MSI MINGW64 /d/source/mnemonist2 (kralcifer/typescript)
$ git push origin kralcifer/typescript
Enter passphrase for key '/d/kralcifer.visualstudio.com/.ssh/id_rsa':
ERROR: Permission to Yomguithereal/mnemonist.git denied to kralcifer.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Yomguithereal** [comment]
Hard to say. it seems your shell tries to push directly to my repo which you are not allowed to do.

**Comment by kralcifer** [comment]
just my newbie-ness.  I need to fork.

**Comment by kralcifer** [comment]
Ok.  Tried latest and I'm getting no matches when I type my first letter because it looks like it only pushes out a match if SENTINEL was reached.  I see your set() also calls what I'm setting in the TrieMap a 'prefix' but I don't want to match the whole string I want a prefix typed by the user to match all strings entered through set(string, any) that start with the prefix the user is typing.  So a set('Sudden Impact VBC', 'fooClubId') with a find('S') would return ['fooClubId'].    Seems like when it runs out of prefix stack it needs to grab any sentinels remaining in nodeStack.

**Comment by kralcifer** [comment]
I put up a PR for start of TypeScript.

**Comment by Yomguithereal** [comment]
> So a set('Sudden Impact VBC', 'fooClubId') with a find('S') would return ['fooClubId']. Seems like when it runs out of prefix stack it needs to grab any sentinels remaining in nodeStack.

Let me check my code once again but normally, it this find call should indeed return ['fooClubId'].

**Comment by Yomguithereal** [comment]
So, if I do the following:

```js
var trie = new TrieMap();
trie.set('Sudden Impact VBC', 1);
console.log(trie.find('S'));
```

I get `[ [ 'Sudden Impact VBC', 1 ] ]`. Isn't that what you want it to do?

**Comment by Yomguithereal** [comment]
Just published `0.20.0` with both `Trie` & `TrieMap` and updated the docs.

**Comment by kralcifer** [comment]
Yes, that's what I want it to do but I was getting no returned matches.  I'll try again to see why.  Thanks for working on it so rapidly!

**Comment by kralcifer** [comment]
It's all working as you said!

I got Trie working with me doing the lookup on the outside last night.  Tonight I put release 20 in and I now have a much smaller amount of code using TrieMap.  Thank you!

**Comment by Yomguithereal** [comment]
My pleasure. Let me close this issue for now then. Don't hesitate to open another one if needed.
