### ISSUE TITLE
[feature request]add unshift method for Circular Buffer

### ISSUE THREAD

**Issue by lianzhao** [Yomguithereal/mnemonist#95]

**Comment by Yomguithereal** [comment]
I will try to add this soon. Out of curiosity, what's your use case?

**Comment by lianzhao** [comment]
Well, I think it's better to erase values. But That will be a break change?

**Comment by Yomguithereal** [comment]
> But That will be a break change?

Yes but that's not an issue since I am under v1 anyway.

What I had in mind was to change `CircularBuffer`'s behavior to erase value and create alongside it a `FixedDeque` that would essentially be the same thing but keeping throwing behavior. Does it sound good to you?

**Comment by lianzhao** [comment]
Sounds good:)

**Comment by Yomguithereal** [comment]
Just published v0.27.0 on npm with the #.unshift method & the distinction between `CircularBuffer` and `FixedDeque`. Tell me if this fits your need.

**Comment by lianzhao** [comment]
Yes! Thank you :)

**Comment by lianzhao** [comment]
eh, one more thing
https://github.com/Yomguithereal/mnemonist/blob/fed54c9f1dc99ac89823f03c548718e14259a145/circular-buffer.d.ts#L21
should be `unshift(item: T): number;`

**Comment by Yomguithereal** [comment]
Just published v0.27.1 with the fix.

**Comment by lianzhao** [comment]
The TS compiler is now satisfied, thanks a lot:)
